### ISSUE TITLE
Automated Testing Sim Error (7/19/2016 10:09 AM)

### ISSUE THREAD

**Issue by phet-steele** [phetsims/protein-synthesis#24] opened 2016-07-19 17:22 UTC
Looks eerily similar to #20.

```
Error: Assertion failed: Attempted to removeChild with a node that was not a child.
    at window.assertions.assertFunction (http://phettest.colorado.edu/assert/js/assert.js:23:13)
    at Node.removeChild (http://phettest.colorado.edu/scenery/js/nodes/Node.js?bust=1468947288386:374:17)
    at http://phettest.colorado.edu/protein-synthesis/js/protein-synthesis/view/ProteinSynthesisScreenView.js?bust=1468947288386:309:23
    at Array.forEach (native)
    at Array. (http://phettest.colorado.edu/protein-synthesis/js/protein-synthesis/view/ProteinSynthesisScreenView.js?bust=1468947288386:305:27)
    at Emitter.emit2 (http://phettest.colorado.edu/axon/js/Emitter.js?bust=1468947288386:139:49)
    at Property._notifyObservers (http://phettest.colorado.edu/axon/js/Property.js?bust=1468947288386:129:29)
    at Property._setAndNotifyObservers (http://phettest.colorado.edu/axon/js/Property.js?bust=1468947288386:117:14)
    at Property.set (http://phettest.colorado.edu/axon/js/Property.js?bust=1468947288386:85:16)
    at Property.set value [as value] (http://phettest.colorado.edu/axon/js/Property.js?bust=1468947288386:158:36)
```

**Comment by jonathanolson** [comment] 2017-02-03 00:34
Also reproducing:
```
protein-synthesis : fuzz : require.js : run
Uncaught Error: Assertion failed: Attempted to removeChild with a node that was not a child.
Error: Assertion failed: Attempted to removeChild with a node that was not a child.
    at window.assertions.assertFunction (http://localhost/snapshot-1486081009161/assert/js/assert.js:21:13)
    at Node.removeChild (http://localhost/snapshot-1486081009161/scenery/js/nodes/Node.js?bust=1486081939608:598:17)
    at http://localhost/snapshot-1486081009161/protein-synthesis/js/protein-synthesis/view/ProteinSynthesisScreenView.js?bust=1486081939608:314:23
    at Array.forEach (native)
    at Array.<anonymous> (http://localhost/snapshot-1486081009161/protein-synthesis/js/protein-synthesis/view/ProteinSynthesisScreenView.js?bust=1486081939608:310:27)
    at Emitter.emit2 (http://localhost/snapshot-1486081009161/axon/js/Emitter.js?bust=1486081939608:147:49)
    at Property._notifyObservers (http://localhost/snapshot-1486081009161/axon/js/Property.js?bust=1486081939608:176:29)
    at Property._setAndNotifyObservers (http://localhost/snapshot-1486081009161/axon/js/Property.js?bust=1486081939608:165:14)
    at Property.set (http://localhost/snapshot-1486081009161/axon/js/Property.js?bust=1486081939608:133:16)
    at Property.set value [as value] (http://localhost/snapshot-1486081009161/axon/js/Property.js?bust=1486081939608:205:36)
Approximately 2/2/2017, 5:16:49 PM
```

**Comment by KatieWoe** [comment] 2022-09-09 18:16
Closing this for https://github.com/phetsims/qa/issues/832 since this sim is no longer tracked by CT. If this is in error, please reopen.

**Closed by KatieWoe** 2022-09-09 18:16 UTC
Labels: priority:5-deferred, type:automated-testing
